nr_api_key: ""
action: "" # create | delete
infra_alerts_host: "https://staging-infra-api.newrelic.com"
alerts_host: "https://staging-api.newrelic.com"
entity_name: "" # i.e. "{{ iid }}:{{ inventory_hostname }}"
policy_name: "" # i.e. "CAOS packaging tests HNR {{ inventory_hostname }}"
